// Code generated by MockGen. DO NOT EDIT.
// Source: ./client.go

// Package apiclient is a generated GoMock package.
package apiclient

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CallSomething mocks base method.
func (m *MockClient) CallSomething(req CallSomethingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallSomething", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CallSomething indicates an expected call of CallSomething.
func (mr *MockClientMockRecorder) CallSomething(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallSomething", reflect.TypeOf((*MockClient)(nil).CallSomething), req)
}
