// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package dosomething

import (
	"github.com/o-aloqaily/go-project-starter/internal/apiclient"
	"github.com/o-aloqaily/go-project-starter/internal/config"
	"github.com/o-aloqaily/go-project-starter/internal/interfaces"
	"github.com/o-aloqaily/go-project-starter/pkg/logger"
	"github.com/o-aloqaily/go-project-starter/pkg/responder"
	"github.com/o-aloqaily/go-project-starter/pkg/validator"
)

// Injectors from wire.go:

func InitializeDoSomethingAPI() interfaces.API {
	loggerLogger := logger.NewLogger()
	configConfig := config.NewConfig(loggerLogger)
	client := apiclient.NewClient(configConfig, loggerLogger)
	dosomethingService := NewService(client)
	validatorValidator := validator.NewValidator()
	responderResponder := responder.NewResponder()
	interfacesAPI := NewAPI(dosomethingService, loggerLogger, validatorValidator, responderResponder)
	return interfacesAPI
}
