// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/o-aloqaily/go-project-starter/internal/config"
	"github.com/o-aloqaily/go-project-starter/pkg/logger"
	"github.com/o-aloqaily/go-project-starter/pkg/router"
)

// Injectors from wire.go:

func InitializeServer() *Server {
	loggerLogger := logger.NewLogger()
	configConfig := config.NewConfig(loggerLogger)
	routerRouter := router.NewRouter()
	server := NewServer(loggerLogger, configConfig, routerRouter)
	return server
}
